# Additional simulator build rules

dirs-y += src/simulator src/generic

src-y += simulator/main.c simulator/gpio.c simulator/timer.c simulator/serial.c
src-y += generic/crc16_ccitt.c generic/alloc.c
src-y += generic/timer_irq.c generic/serial_irq.c
