#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
	echo "Usage: ${0} PATH"
	exit 1
fi

find "${1}" \
	-type f \
	\(	\
		-name '*.o' \
		-o \
		-name '*.obj' \
		-o \
		-name '*.c.obj' \
	\) \
	"${@:2}" \
| sort | uniq
