#!/bin/bash
# Prompt user to confirm they want to uninstall
echo "#### PLEASE MAKE SURE YOU HAVE BACKED UP YOUR CONFIGS IF YOU WISH TO RE-INSTALL ####"
read -p "#### THIS WILL UNINSTALL KLIPPER, ARE YOU SURE? #### - " -n 1 -r 
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]]
then
    exit 1
fi

# Stop Klipper Service
echo "###Stopping Klipper Service.."
echo
sudo service klipper stop

# Remove Klipper from Startup
echo "####Removing Klipper from Startup.."
echo
sudo update-rc.d  -f klipper remove

# Remove Klipper from Services
echo "####Removing Klipper Service"
echo
sudo rm -f /etc/init.d/klipper /etc/default/klipper

# Remove Klipper from Home
echo "####Removing Klipper..." 
echo
sudo rm -rf /home/pi/klippy-env /home/pi/klipper /home/pi/klipper

echo Done!
